modLoader = "kotlinforforge"
loaderVersion = "[3.12.0,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "simplici"
version = "${version}"
displayName = "VS Simplici Mod"
authors = ["Dustley"]
description = '''
VS2 vanilla+ mod
'''
logoFile = "icon.png"

[[dependencies.simplici]]
modId = "forge"
mandatory = true
versionRange = "[47.0.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplici]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplici]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"